# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('organization', models.TextField()),
                ('common_name', models.TextField()),
                ('email', models.TextField()),
                ('surname', models.TextField()),
            ],
        ),
    ]
